#!/bin/sh

# SPDX-FileCopyrightText: Copyright (C) 2021 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

function processExitCode { #(code,message)
    if [ $1 -ne 0 ]
    then
        echo "$2"
        exit 1
    fi
}

#cd to the root of the repo
cd "$(dirname "$0")"
cd ../

#run the linter
echo "Running php-cs-fixer"
./vendor/bin/php-cs-fixer fix --using-cache=no --quiet

processExitCode $? "Something went wrong with php-cs-fixer"

#run phpstan
echo "Analyzing code with phpstan"
./vendor/phpstan/phpstan/phpstan clear-result-cache --quiet
./vendor/phpstan/phpstan/phpstan analyse --quiet

processExitCode $? "Errors found with phpstan ...aborting commit"

#run psalm
echo "Analyzing code with psalm"
./vendor/bin/psalm --no-cache > /dev/null 2>&1

processExitCode $? "Errors found with psalm ...aborting commit"
