# dummy stages to follow the AutoDevOps template guidelines
stages:
  - build
  - test
  - deploy
  - review
  - dast
  - staging
  - canary
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup
  - extra


include: 
  - project: 'opalmedapps/engineering/ci-templates'
    file: '/templates/autodevops/Auto-DevOps.gitlab-ci.yml'
  - component: $CI_SERVER_FQDN/opalmedapps/engineering/ci-templates/check-thirdparty-notice@main
    inputs:
      package-file: package.json
      composer-file: composer.json
