# SPDX-FileCopyrightText: Copyright (C) 2025 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

[default.extend-words]
muhc = "muhc"
# part of SerNum
ser = "ser"
# French
territoires = "territoires"
sur = "sur"
ressources = "ressources"

[files]
extend-exclude = [
    "php/tool/databaseMaintenance/diagnosis/data/processed_codes.json",
    "php/tool/databaseMaintenance/diagnosis/data/raw_codes.json",
]
