#!/usr/bin/perl
#------------------------------------------------------------------------
# J.Kildea 8 august 2017 
#------------------------------------------------------------------------
# PERL-CGI-DBI script to check all patients out 
# 
# Input parameters: none	
#------------------------------------------------------------------------
# Declarations/initialisations
#------------------------------------------------------------------------
use strict;
#use warnings;
#use diagnostics;

#------------------------------------------------------------------------
# Use the DBI module 
#------------------------------------------------------------------------
use DBI;
use DBD::Sybase;
use Date::Calc;
use LWP::Simple;
#use Date::Calc qw( Standard_to_Business Today Business_to_Standard );  
use Date::Calc qw(Day_of_Week_to_Text Day_of_Week Decode_Month Today Now Decode_Date_US Today_and_Now Delta_DHMS Add_Delta_Days Delta_Days Add_Delta_DHMS Day_of_Week_Abbreviation);  

#------------------------------------------------------------------------
# Important variables
#------------------------------------------------------------------------
my $verbose = 0;

#------------------------------------------------------------------------
# Connect to the MUHC MySQL database 
#------------------------------------------------------------------------
my $muhcdb_host="localhost";
my $muhcdb_database="WaitRoomManagement";
my $muhcdb_user="readonly";
my $muhcdb_password="readonly";

my $dbh_mysql =  DBI->connect("DBI:mysql:database=$muhcdb_database;host=$muhcdb_host",$muhcdb_user,$muhcdb_password)
    or die "Couldn't connect to database: " . DBI->errstr;


#------------------------------------------------------------------------
# Get the list of patients listed as currently checked in 
#------------------------------------------------------------------------
my $PatientLocationSQL= "
	SELECT
		Patient.PatientId,
		PatientLocation.AppointmentSerNum	
	FROM
		PatientLocation,
		Patient,
		MediVisitAppointmentList
	WHERE
		PatientLocation.AppointmentSerNum = MediVisitAppointmentList.AppointmentSerNum
		AND MediVisitAppointmentList.PatientSerNum = Patient.PatientSerNum
";
		#AND PatientLocation.ArrivalDatetime > CURDATE() 

print "SQL: $PatientLocationSQL\n" if $verbose;

# prepare query
my $query= $dbh_mysql->prepare($PatientLocationSQL)
  or die "Couldn't prepare statement: " . $dbh_mysql->errstr;

# submit query
$query->execute()
  or die "Couldn't execute statement: " . $query->errstr;

my $PatientId;
my $AppointmentSerNum;

# loop over the still-checkedin appointments
while(my @data = $query->fetchrow_array())
{
  print "Data: @data<br>\n" if $verbose;

  $PatientId 		= $data[0]; 
  $AppointmentSerNum 	= $data[1]; 

  #Checkout this patient for this appointment 
  my $CheckoutURL = "http://172.26.66.41/devDocuments/pilotscreens/php/dischargePatient.php?CheckoutVenue=NightlyAutoCheckOut&PatientId=$PatientId&ScheduledActivitySer=$AppointmentSerNum&Final=1";
  print "Checkout: $CheckoutURL\n" if $verbose;
  my $checkout = get($CheckoutURL); 

  print "PatientId: $PatientId, AppointmentSerNum: $AppointmentSerNum\n" if $verbose;

}

#------------------------------------------------------------------------
# exit gently
#------------------------------------------------------------------------
exit;


