# SPDX-FileCopyrightText: Copyright (C) 2023 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

services:
  memcached:
    image: memcached:1.6.38-alpine3.21
    environment:
      - TZ=EST5EDT

  app:
    build:
      context: .
      args:
        - PHP_ENV=development
    image: opalmedapps/orms
    # TODO: set time zone
    # See: https://dev.to/kakisoft/dockerphp-what-is-the-most-prioritized-timezone-setting-4bk6
    # https://serverfault.com/a/683651
    env_file:
      - .env
    environment:
      - PHP_MEMORY_LIMIT=512M
      - TZ=EST5EDT
    depends_on:
      - memcached
    volumes:
      - ./:/var/www/orms
      # don't overwrite existing content in these directories
      # needed if you want to manage these through the Docker image build process only
      - /var/www/orms/node_modules
      - /var/www/orms/vendor
    ports:
      - ${ORMS_PORT}:8080
