# SPDX-FileCopyrightText: Copyright (C) 2025 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
name: build

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-build-${{ github.event.pull_request.number || '' }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
      - name: Add npmrc
        env:
          NPMRC_FILE: ${{ secrets.NPMRC_FILE }}
        run: |
          echo "$NPMRC_FILE" > .npmrc
      - uses: opalmedapps/.github/.github/actions/docker-build@main
        id: build-image
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ env.IMAGE_NAME }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Test the image
        env:
          TAG: ${{ steps.build-image.outputs.tag }}
        run: docker run --rm "$TAG" php vendor/autoload.php
